const GXErrors =  {

    GXSignUpVerificationValidate:{
        IN_PROGRESS: "ISVALID",
        HAS_BEEN_VALIDATED: "HAS_BEEN_VALIDATED",
        FIALED: "FIALED",
        EXPIRED: "EXPIRED",
        CANCELLED: "CANCELLED",
        INVALID_TOKEN: "INVALID_TOKEN",
        UNKNOWN: "UKNOWN"
    },
    GXSignUpVerification:{
        SUCCESS:"SUCCESS",
        TOO_MANY_REQUEST_PER_SECONDS: "TOO_MANY_REQUEST_PER_SECONDS",
        MISSING_PARAMETERS: "MISSING_PARAMETERS",
        INVALID_PARAMETERS: "INVALID_PARAMETERS",
        INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
        INTERNAL_ERROR: "INTERNAL_ERROR",
        COULD_NOT_PROCESS: "COULD_NOT_PROCESS",
        QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

        CONCURRENT_VERIFICATION_TO_SAME_NUMBER_NOT_ALLOWED: "CONCURRENT_VERIFICATION_TO_SAME_NUMBER_NOT_ALLOWED",
        NUMBER_BLACKLISTED:"NUMBER_BLACKLISTED",
        NUMBER_NOT_IN_SUPPORTED_NETWORK: "NUMBER_NOT_IN_SUPPORTED_NETWORK",
        INCORRECT_UNEXPECTED_CODE: "INCORRECT_UNEXPECTED_CODE",
        TOO_MANY_WRONG_CODES: "TOO_MANY_WRONG_CODES",
        TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
        REQUEST_NOT_FOUND: "REQUEST_NOT_FOUND",
        UNKNOWN : ""
    },

    EVENT_ARGUMENTS_VALIDATION_FAILED:  "EVENT_ARGUMENTS_VALIDATION_FAILED",//{gix:true, code:"EVENT_ARGUMENTS_VALIDATION_FAILED"},

    RDS_DB_POOL_CREATION_ERROR:         "RDS_DB_POOL_CREATION_ERROR",//{gix:true, code:"RDS_DB_POOL_CREATION_ERROR"},
    RDS_DB_CONNECTION_ERROR:            "RDS_DB_CONNECTION_ERROR",//{gix:true, code:"RDS_DB_CONNECTION_ERROR"},


    AUTH_USER_NOT_FOUND:                "AUTH_USER_NOT_FOUND",//{gix:true, code:"AUTH_USER_NOT_FOUND"},
    AUTH_USER_DISABLED:                "AUTH_USER_DISABLED",//{gix:true, code:"AUTH_USER_NOT_FOUND"},
    AUTH_USER_SUSPENDED:                "AUTH_USER_SUSPENDED",//{gix:true, code:"AUTH_USER_NOT_FOUND"},
    AUTH_INCORRECT_PASSWORD:            "AUTH_INCORRECT_PASSWORD",//{gix:true, code:"AUTH_INCORRECT_PASSWORD"},
    AUTH_TOKEN_RETRIEVE_FAILED:         "AUTH_TOKEN_RETRIEVE_FAILED",//{gix:true, code:"AUTH_TOKEN_RETRIEVE_FAILED"},
    AUTH_TOKEN_RETRIEVE_EMPTY:          "AUTH_TOKEN_RETRIEVE_EMPTY",//{gix:true, code:"AUTH_TOKEN_RETRIEVE_EMPTY"},
    AUTH_IDENTITY_ID_RETRIEVE_EMPTY:    "AUTH_IDENTITY_ID_RETRIEVE_EMPTY",//{gix:true, code:"AUTH_IDENTITY_ID_RETRIEVE_EMPTY"},

    ACCOUNT_ALREADY_EXIST:              "ACCOUNT_ALREADY_EXIST",//{gix:true, code:"ACCOUNT_ALREADY_EXIST"},
    ACCOUNT_DOESNOT_EXIST:              "ACCOUNT_DOESNOT_EXIST",//{gix:true, code:"ACCOUNT_DOESNOT_EXIST", message:"Account Does not exist."},


    SIGNUP_DEVICE_UUID_BLACKLISTED : "SIGNUP_DEVICE_UUID_BLACKLISTED",
    SIGNUP_PROTECTION_INVALID_PHONENUMBER: "SIGNUP_PROTECTION_INVALID_PHONENUMBER",
    SIGNUP_PROTECTION_PIN_REQUIRED:     "SIGNUP_PROTECTION_PIN_REQUIRED",
    SIGNUP_PROTECTION_PIN_INCORRECT:    "SIGNUP_PROTECTION_PIN_INCORRECT",
    SIGNUP_MFA_TOOMANY_WRONG_CODE:      "SIGNUP_MFA_TOOMANY_WRONG_CODE",
    SIGNUP_MFA_TOO_SOON_TO_REQUEST:     "SIGNUP_MFA_TOO_SOON_TO_REQUEST",
    SIGNUP_MFA_BLACKLISTED_PHONENUMBER: "SIGNUP_MFA_BLACKLISTED_PHONENUMBER",
    SIGNUP_DEVICE_UUID_MISMATCH:        "SIGNUP_DEVICE_UUID_MISMATCH",
    SIGNUP_CONFIRM_PHONENUMBER_EMPTY:           "SIGNUP_CONFIRM_PHONENUMBER_EMPTY",
    SIGNUP_CONFIRM_PIN_EMPTY:           "SIGNUP_CONFIRM_PIN_EMPTY",
    SIGNUP_CONFIRM_PIN_MISMATCH:        "SIGNUP_CONFIRM_PIN_MISMATCH",
    SIGNUP_TEMP_ERROR:                  "SIGNUP_TEMP_ERROR",

    CONFIRMSIGNUP_RESTART_SIGNUP_REQUIRED:  "CONFIRMSIGNUP_RESTART_SIGNUP_REQUIRED",

    DYNAMODB_RESULTS_ITEM_EMPTY:        "DYNAMODB_RESULTS_ITEM_EMPTY",//{gix:true, code:"DYNAMODB_RESULTS_ITEM_EMPTY"},
    DYNAMODB_BATCH_HAS_UNPROCESSED_ITEMS:        "DYNAMODB_BATCH_HAS_UNPROCESSED_ITEMS",//{gix:true, code:"DYNAMODB_BATCH_HAS_UNPROCESSED_ITEMS"},
    DYNAMODB_UNMARSHALED_ITEM_EMPTY:        "DYNAMODB_UNMARSHALED_ITEM_EMPTY",//{gix:true, code:"DYNAMODB_UNMARSHALED_ITEM_EMPTY"},
    DYNAMODB_ATTRIBUTE_TYPE_VALIDATION_FAILED:        "DYNAMODB_ATTRIBUTE_TYPE_VALIDATION_FAILED", //{gix:true, code:"DYNAMODB_ATTRIBUTE_TYPE_VALIDATION_FAILED"}

    ADMIN_ACCOUNT_NOT_FOUND: "ADMIN_ACCOUNT_NOT_FOUND",

    GRAPHQL_ACOUNT_NOT_FOUND:"GRAPHQL_ACOUNT_NOT_FOUND",

    GRAPH_DB_FAILED: "GRAPH_DB_FAILED",
    GRAPH_DB_FAILED_WITH_CRITICAL_ERROR: "GRAPH_DB_FAILED_WITH_CRITICAL_ERROR",
    GRAPH_DB_UPDATE_OR_ADD_CONTACTS_FAILED_EMPTY_UPDATE_LIST: "GRAPH_DB_UPDATE_OR_ADD_CONTACTS_FAILED_EMPTY_UPDATE_LIST",
    GRAPH_DB_UPDATE_OR_ADD_CONTACTS_FAILED_LIST_NOT_ARRAY:"GRAPH_DB_UPDATE_OR_ADD_CONTACTS_FAILED_LIST_NOT_ARRAY",


    GRAPH_DB_REQUEST_OWNER_VERTEX_NOT_FOUND: "GRAPH_DB_REQUEST_OWNER_VERTEX_NOT_FOUND",

    GRAPH_MUTATION_UNAUTHORIZED: "GRAPH_MUTATION_UNAUTHORIZED",

    IAP_PURCHASE_INVALID_PROVIDER: "IAP_PURCHASE_INVALID_PROVIDER",
    IAP_PURCHASE_IDENTIFIER_FOUND_ON_DB: "IAP_PURCHASE_IDENTIFIER_FOUND_ON_DB",
    IAP_PURCHASE_WRITE_TO_DB_DUPLICATE_ITEM: "IAP_PURCHASE_WRITE_TO_DB_DUPLICATE_ITEM",


    DID_PURCHASE_FAILED_NUMBER_NOT_AVAILABLE: "DID_PURCHASE_FAILED_NUMBER_NOT_AVAILABLE",  /// May be someone else already bought the number
    DID_PURCHASE_FAILED_NUMBER_NOT_FOUND:"DID_PURCHASE_FAILED_NUMBER_NOT_FOUND",
    DID_PURCHASE_FAILED_NUMBER_MORE_THAN_ONE: "DID_PURCHASE_FAILED_NUMBER_MORE_THAN_ONE",
    DID_PURCHASE_FAILED_NOT_ENOUGH_CREDIT:"DID_PURCHASE_FAILED_NOT_ENOUGH_CREDIT",
    DID_PURCHASE_TEMPORARY_FAILURE_TRY_AGAIN: "DID_PURCHASE_TEMPORARY_FAILURE_TRY_AGAIN",
    DID_PURCHASE_FAILED_ALREADY_OWNED_NUMBER_VALID: "DID_PURCHASE_FAILED_ALREADY_OWNED_NUMBER_VALID",

    SUBSCRIPTION_ITEM_IS_EXPIRED: "SUBSCRIPTION_ITEM_IS_EXPIRED",

    SUBSCRIPTION_FAILED_NOT_FOUND:"SUBSCRIPTION_FAILED_NOT_FOUND",
    PURCHASE_FAILED_NOT_ENOUGH_CREDIT: "PURCHASE_FAILED_NOT_ENOUGH_CREDIT",



    S3_UPLOAD_FAILED_FILE_NOT_FOUND: "S3_UPLOAD_FAILED_FILE_NOT_FOUND",

};


module.exports = GXErrors;